name: Update data

on:  
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Update data
        run: bun update.ts

      - name: Commit changes
        run: |
          git config --local user.name "Kruithne"
          git config --local user.email "kruithne@gmail.com"
          git add .
          git commit -m "Automatic data update"
          git push